import type { Category } from '@stash/core';
import { homedir } from 'os';
import { join } from 'path';

const HOME = homedir();
const APPDATA = process.env.APPDATA || join(HOME, 'AppData', 'Roaming');
const LOCALAPPDATA = process.env.LOCALAPPDATA || join(HOME, 'AppData', 'Local');
const TEMP = process.env.TEMP || join(LOCALAPPDATA, 'Temp');

export const categories: Category[] = [
  // ──── Safe (green) — one-click cleanup ────
  {
    id: 'npm',
    name: 'npm Cache',
    risk: 'safe',
    description: 'npm package cache. Safe to clean.',
    paths: [join(APPDATA, 'npm-cache')],
    cleanCommand: 'npm cache clean --force',
    detectCommand: 'where npm',
  },
  {
    id: 'yarn',
    name: 'Yarn Cache',
    risk: 'safe',
    description: 'Yarn package manager cache. Safe to clean, packages re-download as needed.',
    paths: [join(LOCALAPPDATA, 'Yarn', 'Cache')],
    cleanCommand: 'yarn cache clean',
    detectCommand: 'where yarn',
  },
  {
    id: 'pnpm',
    name: 'pnpm Store',
    risk: 'safe',
    description: 'pnpm content-addressable store. Safe to prune unused packages.',
    paths: [join(LOCALAPPDATA, 'pnpm', 'store')],
    cleanCommand: 'pnpm store prune',
    detectCommand: 'where pnpm',
  },
  {
    id: 'pip',
    name: 'pip Cache',
    risk: 'safe',
    description: 'Python pip download cache. Safe to purge.',
    paths: [join(LOCALAPPDATA, 'pip', 'Cache')],
    cleanCommand: 'pip cache purge',
    detectCommand: 'where pip',
  },
  {
    id: 'nuget',
    name: 'NuGet Cache',
    risk: 'safe',
    description: 'NuGet package cache. Re-downloads as needed.',
    paths: [join(LOCALAPPDATA, 'NuGet', 'v3-cache'), join(HOME, '.nuget', 'packages')],
    cleanCommand: 'dotnet nuget locals all --clear',
    detectCommand: 'where dotnet',
  },
  {
    id: 'gradle',
    name: 'Gradle Cache',
    risk: 'safe',
    description: 'Gradle build cache and downloaded dependencies.',
    paths: [join(HOME, '.gradle', 'caches')],
    cleanCommand: `powershell -NoProfile -Command "Remove-Item -Recurse -Force '${join(HOME, '.gradle', 'caches')}\\*'"`,
    detectCommand: 'where gradle',
  },
  {
    id: 'maven',
    name: 'Maven Local Repository',
    risk: 'safe',
    description: 'Maven cached artifacts. Re-downloads as needed.',
    paths: [join(HOME, '.m2', 'repository')],
    cleanCommand: `powershell -NoProfile -Command "Remove-Item -Recurse -Force '${join(HOME, '.m2', 'repository')}\\*'"`,
  },
  {
    id: 'cargo',
    name: 'Cargo Registry Cache',
    risk: 'safe',
    description: 'Rust Cargo registry cache. Re-downloads as needed.',
    paths: [join(HOME, '.cargo', 'registry')],
    cleanCommand: `powershell -NoProfile -Command "Remove-Item -Recurse -Force '${join(HOME, '.cargo', 'registry', 'cache')}\\*', '${join(HOME, '.cargo', 'registry', 'src')}\\*'"`,
    detectCommand: 'where cargo',
  },
  {
    id: 'go-cache',
    name: 'Go Module Cache',
    risk: 'safe',
    description: 'Go module download cache. Re-downloads when needed.',
    paths: [join(HOME, 'go', 'pkg', 'mod', 'cache'), join(LOCALAPPDATA, 'go-build')],
    cleanCommand: 'go clean -modcache && go clean -cache',
    detectCommand: 'where go',
  },
  {
    id: 'composer',
    name: 'Composer Cache',
    risk: 'safe',
    description: 'PHP Composer package cache. Re-downloads on next install.',
    paths: [join(LOCALAPPDATA, 'Composer'), join(HOME, '.composer', 'cache')],
    cleanCommand: 'composer clear-cache',
    detectCommand: 'where composer',
  },
  {
    id: 'typescript',
    name: 'TypeScript Cache',
    risk: 'safe',
    description: 'TypeScript compiler cache files.',
    paths: [join(LOCALAPPDATA, 'Microsoft', 'TypeScript')],
    cleanCommand: `powershell -NoProfile -Command "Remove-Item -Recurse -Force '${join(LOCALAPPDATA, 'Microsoft', 'TypeScript')}\\*'"`,
  },
  {
    id: 'playwright',
    name: 'Playwright Cache',
    risk: 'safe',
    description: 'Playwright browser binaries cache. Re-downloads when needed.',
    paths: [join(LOCALAPPDATA, 'ms-playwright')],
    cleanCommand: `powershell -NoProfile -Command "Remove-Item -Recurse -Force '${join(LOCALAPPDATA, 'ms-playwright')}\\*'"`,
  },
  {
    id: 'electron',
    name: 'Electron Cache',
    risk: 'safe',
    description: 'Cached Electron binaries from builds.',
    paths: [join(LOCALAPPDATA, 'electron', 'Cache')],
    cleanCommand: `powershell -NoProfile -Command "Remove-Item -Recurse -Force '${join(LOCALAPPDATA, 'electron', 'Cache')}\\*'"`,
  },
  {
    id: 'windows-temp',
    name: 'Windows Temp Files',
    risk: 'safe',
    description: 'Temporary files. Safe to clean (in-use files are skipped).',
    paths: [TEMP],
    cleanCommand: `powershell -NoProfile -Command "Get-ChildItem -Path '${TEMP}' -Recurse -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue"`,
  },
  {
    id: 'docker',
    name: 'Docker (dangling images/containers)',
    risk: 'safe',
    description: 'Unused Docker images, containers, and build cache.',
    paths: [join(LOCALAPPDATA, 'Docker')],
    cleanCommand: 'docker system prune -f',
    detectCommand: 'where docker',
  },
  {
    id: 'chrome-cache',
    name: 'Google Chrome Cache',
    risk: 'safe',
    description: 'Chrome browser cache. Rebuilds automatically.',
    paths: [join(LOCALAPPDATA, 'Google', 'Chrome', 'User Data', 'Default', 'Cache')],
    cleanCommand: `powershell -NoProfile -Command "Remove-Item -Recurse -Force '${join(LOCALAPPDATA, 'Google', 'Chrome', 'User Data', 'Default', 'Cache')}\\*'"`,
  },
  {
    id: 'edge-cache',
    name: 'Microsoft Edge Cache',
    risk: 'safe',
    description: 'Edge browser cache. Rebuilds automatically.',
    paths: [join(LOCALAPPDATA, 'Microsoft', 'Edge', 'User Data', 'Default', 'Cache')],
    cleanCommand: `powershell -NoProfile -Command "Remove-Item -Recurse -Force '${join(LOCALAPPDATA, 'Microsoft', 'Edge', 'User Data', 'Default', 'Cache')}\\*'"`,
  },
  {
    id: 'vs-cache',
    name: 'Visual Studio Cache',
    risk: 'safe',
    description: 'Visual Studio component cache and MEF cache.',
    paths: [
      join(LOCALAPPDATA, 'Microsoft', 'VisualStudio', 'Packages'),
      join(LOCALAPPDATA, 'Microsoft', 'VisualStudio', 'ComponentModelCache'),
    ],
    cleanCommand: `powershell -NoProfile -Command "Remove-Item -Recurse -Force '${join(LOCALAPPDATA, 'Microsoft', 'VisualStudio', 'ComponentModelCache')}\\*'"`,
    detectCommand: 'where devenv',
  },
  {
    id: 'vscode-cache',
    name: 'VS Code Cache',
    risk: 'safe',
    description: 'VS Code cached data. Rebuilds automatically.',
    paths: [join(APPDATA, 'Code', 'Cache'), join(APPDATA, 'Code', 'CachedData')],
    cleanCommand: `powershell -NoProfile -Command "Remove-Item -Recurse -Force '${join(APPDATA, 'Code', 'Cache')}\\*', '${join(APPDATA, 'Code', 'CachedData')}\\*'"`,
  },

  // ──── Selective (yellow) ────
  {
    id: 'android-sdk',
    name: 'Android SDK',
    risk: 'selective',
    description: 'Android SDK platforms and build tools. Pick versions to remove.',
    paths: [join(LOCALAPPDATA, 'Android', 'Sdk')],
    detectCommand: 'where sdkmanager',
  },
  {
    id: 'android-emulators',
    name: 'Android Emulators',
    risk: 'selective',
    description: 'Android Virtual Devices. Pick which emulators to delete.',
    paths: [join(HOME, '.android', 'avd')],
    detectCommand: 'where emulator',
  },

  // ──── Display only (gray) ────
  {
    id: 'downloads',
    name: 'Downloads',
    risk: 'display-only',
    description: 'Your Downloads folder. Shown for awareness only.',
    paths: [join(HOME, 'Downloads')],
  },
  {
    id: 'recycle-bin',
    name: 'Recycle Bin',
    risk: 'display-only',
    description: 'Your Recycle Bin. Shown for awareness only.',
    paths: ['C:\\$Recycle.Bin'],
  },
];
