import type { Category } from '@stash/core';
import { homedir } from 'os';
import { join } from 'path';

const HOME = homedir();
const XDG_CACHE = process.env.XDG_CACHE_HOME || join(HOME, '.cache');
const XDG_DATA = process.env.XDG_DATA_HOME || join(HOME, '.local', 'share');

export const categories: Category[] = [
  // ──── Safe (green) — one-click cleanup ────
  {
    id: 'npm',
    name: 'npm Cache',
    risk: 'safe',
    description: 'npm package cache. Safe to clean.',
    paths: [join(HOME, '.npm', '_cacache')],
    cleanCommand: 'npm cache clean --force',
    detectCommand: 'which npm',
  },
  {
    id: 'yarn',
    name: 'Yarn Cache',
    risk: 'safe',
    description: 'Yarn package manager cache. Safe to clean, packages re-download as needed.',
    paths: [join(XDG_CACHE, 'yarn'), join(HOME, '.cache', 'yarn')],
    cleanCommand: 'yarn cache clean',
    detectCommand: 'which yarn',
  },
  {
    id: 'pnpm',
    name: 'pnpm Store',
    risk: 'safe',
    description: 'pnpm content-addressable store. Safe to prune unused packages.',
    paths: [join(XDG_DATA, 'pnpm', 'store'), join(HOME, '.local', 'share', 'pnpm', 'store')],
    cleanCommand: 'pnpm store prune',
    detectCommand: 'which pnpm',
  },
  {
    id: 'pip',
    name: 'pip Cache',
    risk: 'safe',
    description: 'Python pip download cache. Safe to purge.',
    paths: [join(XDG_CACHE, 'pip'), join(HOME, '.cache', 'pip')],
    cleanCommand: 'pip cache purge',
    detectCommand: 'which pip',
  },
  {
    id: 'gradle',
    name: 'Gradle Cache',
    risk: 'safe',
    description: 'Gradle build cache and downloaded dependencies.',
    paths: [join(HOME, '.gradle', 'caches')],
    cleanCommand: `rm -rf "${join(HOME, '.gradle', 'caches')}"/*`,
    detectCommand: 'which gradle',
  },
  {
    id: 'maven',
    name: 'Maven Local Repository',
    risk: 'safe',
    description: 'Maven cached artifacts. Re-downloads as needed.',
    paths: [join(HOME, '.m2', 'repository')],
    cleanCommand: `rm -rf "${join(HOME, '.m2', 'repository')}"/*`,
  },
  {
    id: 'cargo',
    name: 'Cargo Registry Cache',
    risk: 'safe',
    description: 'Rust Cargo registry cache and git checkouts. Re-downloads as needed.',
    paths: [join(HOME, '.cargo', 'registry')],
    cleanCommand: `rm -rf "${join(HOME, '.cargo', 'registry', 'cache')}"/* "${join(HOME, '.cargo', 'registry', 'src')}"/*`,
    detectCommand: 'which cargo',
  },
  {
    id: 'go-cache',
    name: 'Go Module Cache',
    risk: 'safe',
    description: 'Go module download cache. Re-downloads when needed.',
    paths: [join(HOME, 'go', 'pkg', 'mod', 'cache'), join(XDG_CACHE, 'go-build')],
    cleanCommand: 'go clean -modcache && go clean -cache',
    detectCommand: 'which go',
  },
  {
    id: 'composer',
    name: 'Composer Cache',
    risk: 'safe',
    description: 'PHP Composer package cache. Re-downloads on next install.',
    paths: [join(XDG_CACHE, 'composer'), join(HOME, '.composer', 'cache')],
    cleanCommand: 'composer clear-cache',
    detectCommand: 'which composer',
  },
  {
    id: 'ruby-gems',
    name: 'Ruby Gems Cache',
    risk: 'safe',
    description: 'Ruby gem download cache. Re-downloads as needed.',
    paths: [join(HOME, '.gem')],
    cleanCommand: 'gem cleanup && gem sources --clear-all',
    detectCommand: 'which gem',
  },
  {
    id: 'typescript',
    name: 'TypeScript Cache',
    risk: 'safe',
    description: 'TypeScript compiler cache files.',
    paths: [join(XDG_CACHE, 'typescript')],
    cleanCommand: `rm -rf "${join(XDG_CACHE, 'typescript')}"/*`,
  },
  {
    id: 'playwright',
    name: 'Playwright Cache',
    risk: 'safe',
    description: 'Playwright browser binaries cache. Re-downloads when needed.',
    paths: [join(XDG_CACHE, 'ms-playwright')],
    cleanCommand: `rm -rf "${join(XDG_CACHE, 'ms-playwright')}"/*`,
  },
  {
    id: 'electron',
    name: 'Electron Cache',
    risk: 'safe',
    description: 'Cached Electron binaries from builds.',
    paths: [join(XDG_CACHE, 'electron')],
    cleanCommand: `rm -rf "${join(XDG_CACHE, 'electron')}"/*`,
  },
  {
    id: 'docker',
    name: 'Docker (dangling images/containers)',
    risk: 'safe',
    description: 'Unused Docker images, containers, and build cache.',
    paths: ['/var/lib/docker'],
    cleanCommand: 'docker system prune -f',
    detectCommand: 'which docker',
  },
  {
    id: 'chrome-cache',
    name: 'Google Chrome Cache',
    risk: 'safe',
    description: 'Chrome browser cache. Rebuilds automatically.',
    paths: [join(XDG_CACHE, 'google-chrome')],
    cleanCommand: `rm -rf "${join(XDG_CACHE, 'google-chrome', 'Default', 'Cache')}"/*`,
  },
  {
    id: 'firefox-cache',
    name: 'Firefox Cache',
    risk: 'safe',
    description: 'Firefox browser cache. Rebuilds automatically.',
    paths: [join(XDG_CACHE, 'mozilla', 'firefox')],
    cleanCommand: `rm -rf "${join(XDG_CACHE, 'mozilla', 'firefox')}"/*`,
  },
  {
    id: 'thumbnails',
    name: 'Thumbnail Cache',
    risk: 'safe',
    description: 'Desktop thumbnail previews. Regenerates automatically.',
    paths: [join(XDG_CACHE, 'thumbnails')],
    cleanCommand: `rm -rf "${join(XDG_CACHE, 'thumbnails')}"/*`,
  },
  {
    id: 'trash',
    name: 'Trash',
    risk: 'safe',
    description: 'Files in your trash. Permanently deletes them.',
    paths: [join(XDG_DATA, 'Trash'), join(HOME, '.local', 'share', 'Trash')],
    cleanCommand: `rm -rf "${join(XDG_DATA, 'Trash', 'files')}"/* "${join(XDG_DATA, 'Trash', 'info')}"/*`,
  },
  {
    id: 'journalctl',
    name: 'System Journal Logs',
    risk: 'safe',
    description: 'Old systemd journal logs. Keeps last 7 days.',
    paths: ['/var/log/journal'],
    cleanCommand: 'sudo journalctl --vacuum-time=7d',
    detectCommand: 'which journalctl',
  },
  {
    id: 'apt-cache',
    name: 'APT Cache',
    risk: 'safe',
    description: 'Downloaded .deb package cache. Re-downloads as needed.',
    paths: ['/var/cache/apt/archives'],
    cleanCommand: 'sudo apt-get clean',
    detectCommand: 'which apt-get',
  },
  {
    id: 'snap-cache',
    name: 'Snap Cache',
    risk: 'safe',
    description: 'Old Snap package revisions. Keeps current version.',
    paths: [join(HOME, 'snap')],
    cleanCommand: 'sudo snap set system refresh.retain=2',
    detectCommand: 'which snap',
  },
  {
    id: 'flatpak',
    name: 'Flatpak Unused Runtimes',
    risk: 'safe',
    description: 'Unused Flatpak runtimes. Removes orphaned dependencies.',
    paths: [join(HOME, '.local', 'share', 'flatpak')],
    cleanCommand: 'flatpak uninstall --unused -y',
    detectCommand: 'which flatpak',
  },
  {
    id: 'vscode-cache',
    name: 'VS Code Cache',
    risk: 'safe',
    description: 'VS Code cached data. Rebuilds automatically.',
    paths: [join(XDG_CACHE, 'Code'), join(HOME, '.config', 'Code', 'Cache')],
    cleanCommand: `rm -rf "${join(XDG_CACHE, 'Code')}"/* "${join(HOME, '.config', 'Code', 'Cache')}"/*`,
  },

  // ──── Selective (yellow) ────
  {
    id: 'android-sdk',
    name: 'Android SDK',
    risk: 'selective',
    description: 'Android SDK platforms and build tools. Pick versions to remove.',
    paths: [join(HOME, 'Android', 'Sdk', 'platforms')],
    detectCommand: 'which sdkmanager',
  },
  {
    id: 'android-emulators',
    name: 'Android Emulators',
    risk: 'selective',
    description: 'Android Virtual Devices. Pick which emulators to delete.',
    paths: [join(HOME, '.android', 'avd')],
    detectCommand: 'which emulator',
  },

  // ──── Display only (gray) ────
  {
    id: 'downloads',
    name: 'Downloads',
    risk: 'display-only',
    description: 'Your Downloads folder. Shown for awareness only.',
    paths: [join(HOME, 'Downloads')],
  },
];
