import type { Category } from '@stash/core';
import { homedir } from 'os';

const HOME = homedir();

export const categories: Category[] = [
  // Safe (green) — one-click cleanup
  {
    id: 'yarn',
    name: 'Yarn Cache',
    risk: 'safe',
    description: 'Yarn package manager cache. Safe to clean, packages re-download as needed.',
    paths: [`${HOME}/Library/Caches/Yarn`],
    cleanCommand: 'yarn cache clean',
    detectCommand: 'which yarn',
  },
  {
    id: 'pnpm',
    name: 'pnpm Store',
    risk: 'safe',
    description: 'pnpm content-addressable store. Safe to prune unused packages.',
    paths: [`${HOME}/Library/pnpm/store`],
    cleanCommand: 'pnpm store prune',
    detectCommand: 'which pnpm',
  },
  {
    id: 'npm',
    name: 'npm Cache',
    risk: 'safe',
    description: 'npm package cache. Safe to clean.',
    paths: [`${HOME}/.npm/_cacache`],
    cleanCommand: 'npm cache clean --force',
    detectCommand: 'which npm',
  },
  {
    id: 'homebrew',
    name: 'Homebrew Cache',
    risk: 'safe',
    description: 'Old Homebrew downloads and logs. Safe to remove.',
    paths: [`${HOME}/Library/Caches/Homebrew`],
    cleanCommand: 'brew cleanup --prune=all',
    detectCommand: 'which brew',
  },
  {
    id: 'pip',
    name: 'pip Cache',
    risk: 'safe',
    description: 'Python pip download cache. Safe to purge.',
    paths: [`${HOME}/Library/Caches/pip`],
    cleanCommand: 'pip cache purge',
    detectCommand: 'which pip',
  },
  {
    id: 'xcode-derived',
    name: 'Xcode Derived Data',
    risk: 'safe',
    description: 'Xcode build artifacts. Rebuilds automatically when you open a project.',
    paths: [`${HOME}/Library/Developer/Xcode/DerivedData`],
    cleanCommand: `rm -rf "${HOME}/Library/Developer/Xcode/DerivedData"/*`,
    detectCommand: 'which xcodebuild',
  },
  {
    id: 'typescript',
    name: 'TypeScript Cache',
    risk: 'safe',
    description: 'TypeScript compiler cache files.',
    paths: [`${HOME}/Library/Caches/typescript`],
    cleanCommand: `rm -rf "${HOME}/Library/Caches/typescript"/*`,
  },
  {
    id: 'playwright',
    name: 'Playwright Cache',
    risk: 'safe',
    description: 'Playwright browser binaries cache. Re-downloads when needed.',
    paths: [`${HOME}/Library/Caches/ms-playwright`],
    cleanCommand: `rm -rf "${HOME}/Library/Caches/ms-playwright"/*`,
  },
  {
    id: 'electron',
    name: 'Electron Cache',
    risk: 'safe',
    description: 'Cached Electron binaries from builds.',
    paths: [`${HOME}/Library/Caches/electron`],
    cleanCommand: `rm -rf "${HOME}/Library/Caches/electron"/*`,
  },
  {
    id: 'cocoapods',
    name: 'CocoaPods Cache',
    risk: 'safe',
    description: 'CocoaPods pod cache. Re-downloads on next install.',
    paths: [`${HOME}/Library/Caches/CocoaPods`],
    cleanCommand: 'pod cache clean --all',
    detectCommand: 'which pod',
  },
  {
    id: 'gradle',
    name: 'Gradle Cache',
    risk: 'safe',
    description: 'Gradle build cache and downloaded dependencies.',
    paths: [`${HOME}/.gradle/caches`],
    cleanCommand: `rm -rf "${HOME}/.gradle/caches"/*`,
    detectCommand: 'which gradle',
  },
  {
    id: 'maven',
    name: 'Maven Local Repository',
    risk: 'safe',
    description: 'Maven cached artifacts. Re-downloads as needed.',
    paths: [`${HOME}/.m2/repository`],
    cleanCommand: `rm -rf "${HOME}/.m2/repository"/*`,
  },
  {
    id: 'docker',
    name: 'Docker (dangling images/containers)',
    risk: 'safe',
    description: 'Unused Docker images, containers, and build cache.',
    paths: [`${HOME}/Library/Containers/com.docker.docker/Data`],
    cleanCommand: 'docker system prune -f',
    detectCommand: 'which docker',
  },
  {
    id: 'chrome-cache',
    name: 'Google Chrome Cache',
    risk: 'safe',
    description: 'Chrome browser cache. Rebuilds automatically.',
    paths: [`${HOME}/Library/Caches/Google/Chrome`],
    cleanCommand: `rm -rf "${HOME}/Library/Caches/Google/Chrome"/*`,
  },

  // Selective (yellow)
  {
    id: 'ios-simulators',
    name: 'iOS Simulators',
    risk: 'selective',
    description: 'Xcode iOS Simulator runtimes. Pick which ones to remove.',
    paths: [
      `${HOME}/Library/Developer/CoreSimulator/Devices`,
      '/Library/Developer/CoreSimulator/Profiles/Runtimes',
    ],
    detectCommand: 'which xcrun',
  },
  {
    id: 'android-sdk',
    name: 'Android SDK',
    risk: 'selective',
    description: 'Android SDK platforms and build tools. Pick versions to remove.',
    paths: [`${HOME}/Library/Android/sdk`],
    detectCommand: 'which sdkmanager',
  },
  {
    id: 'android-emulators',
    name: 'Android Emulators',
    risk: 'selective',
    description: 'Android Virtual Devices. Pick which emulators to delete.',
    paths: [`${HOME}/.android/avd`],
    detectCommand: 'which emulator',
  },

  // Display only (gray)
  {
    id: 'screen-recordings',
    name: 'Screen Recordings',
    risk: 'display-only',
    description: 'Your screen recordings. Shown for awareness only.',
    paths: [`${HOME}/Desktop`, `${HOME}/Movies`],
  },
  {
    id: 'downloads',
    name: 'Downloads',
    risk: 'display-only',
    description: 'Your Downloads folder. Shown for awareness only.',
    paths: [`${HOME}/Downloads`],
  },
];
